run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - gosec
    - gocyclo
    - goconst
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unparam
    - misspell
    - nakedret
    - prealloc
    - gosimple
    - gochecknoinits
    - testpackage
    - funlen
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck